server:
  port: ${PORT:8080}
spring:
  application:
    name: Photovoltaic-projects-manager
  datasource:
    url: ${DATASOURCE_URL}?sslmode=require&connectTimeout=10&socketTimeout=10
    hikari:
      maximum-pool-size: 15
      maximum-idle: 8
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format-sql: false
    show-sql: false
vaadin:
  production-mode: true
logging:
  level:
    root: INFO
    com.github.PatrykKukula.Photovoltaic.materials.calculator: INFO